# Generated by Django 4.2.6 on 2023-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacation_date_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Конец отпуска'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacation_date_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Начало отпуска'),
        ),
    ]
