# Generated by Django 4.2.6 on 2023-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_vacation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vacation_date_end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vacation_date_start',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
