# Generated by Django 4.2.6 on 2023-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_vacation_vacation_date_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin")],
                default="user",
                max_length=10,
                verbose_name="Роль пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="vacation",
            name="vacation_date_end",
            field=models.DateField(blank=True, null=True, verbose_name="Конец отпуска"),
        ),
        migrations.AlterField(
            model_name="vacation",
            name="vacation_date_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Начало отпуска"
            ),
        ),
    ]
